### ISSUE TITLE
'ComputeManagementClient' object has no attribute 'web_apps'

### ISSUE THREAD

**Issue by HemantAHK** [chaostoolkit-incubator/chaostoolkit-azure#118]
Unable to perform an Action.

I tried  restart_app actions but below is the error which I got. can anyone help me out

`[2020-08-xx xx:xx:xx ERROR]   => failed: AttributeError: 'ComputeManagementClient' object has no attribute 'web_apps'`

**Comment by ianalderman** [comment]
I am having this issue too and can see you have a PR to fix it.  I take it there is no way around it until it is accepted? :(
