### ISSUE TITLE
Chaos Azure Extensions and Discovery Not happening

### ISSUE THREAD

**Issue by purwarmayank** [chaostoolkit-incubator/chaostoolkit-azure#128]
Dear Chaos Toolkit team,

Till 2 days back all the Azure discovery was working fine , but since last 2 days its not working , getting below error and even the page (https://docs.chaostoolkit.org/drivers/azure/) is blank , kindly let us know whats the issues here:

Discovery Issue:
could not import extension module 'chaosazure.machine.actions'

**Comment by Lawouach** [comment]
Yeah, sadly the dependencies seem to have changed but I can't tell exactly why/ I guess we could ping to older version of the underlying python deps?

**Comment by Lawouach** [comment]
should be fixed in 0.9.0

**Comment by Lawouach** [comment]
If you keep seeing this error folks, please make sure to update the Python dependencies too.
