### ISSUE TITLE
Switch requirements for Azure Management

### ISSUE THREAD

**Issue by seriousscorpion** [chaostoolkit-incubator/chaostoolkit-azure#17]
The Azure CLI provides full support to manage the Azure infrastructure. Only some advantages:
* with the Azure CLI you can list all available accounts for the Azure CosmosDB
* filter Azure resources with the Azure Graph query language

Switch from azure-mgmt-* modules to the Azure CLI.

**Comment by Lawouach** [comment]
I assume they cover what was done with the previous included dependencies?

**Comment by seriousscorpion** [comment]
Indeed. The Azure CLI covers all previously included dependencies. Additionally it enriches much more functionality.
