### ISSUE TITLE
Reconsider deleting actions

### ISSUE THREAD

**Issue by buderre** [chaostoolkit-incubator/chaostoolkit-azure#30]
Delete actions are invasive actions. They potentially can harm your infrastructure. We should reconsider whether the Azure extension should offer those type of actions. At the moment the *machine* and *aks* modules offer such delete actions. Maybe we should remove them. *Powering off* instead of deleting should be sufficient here.

**Comment by russmiles** [comment]
This is an excellent point. I wonder if some sort of docstring level warning of the destructive nature, plus a pointer to the less destructive actions, would be enough? I guess I can imagine why deletion would be needed is all, and so removing them seems a little prescriptive (although I'm happy to be shouted down on that one).
