### ISSUE TITLE
Discussion: Separate the chaostoolkit-azure extension in two extensions

### ISSUE THREAD

**Issue by buderre** [chaostoolkit-incubator/chaostoolkit-azure#49]
The ct-azure extension hosts actions for *i)* the Azure Service Fabric and *ii)* the Azure infrastructure.

The Azure Service Fabric is an orchestration framework, comparable to K8s. Microsoft states that Service Fabric is portable, and can be deployed on for example [AWS](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-standalone-create-infrastructure).

Some main points for the discussion of separating those two parts:
* The Azure Service Fabric differs in its *business scope* from the Azure infrastructure
* The Azure Service Fabric differs in its authentication logic from the Azure infrastructure authentication
* The Azure Service Fabric as an orchestration framework shall maybe treated like the K8s extension

From the ct clients' point of view, it could also be beneficial to see, that ct supports Azure and Azure Service Fabric.

What do you think?

**Comment by Lawouach** [comment]
Hey @buderre 

I can see the rationale for this completely. I think it showed my lack of understanding of Azure when I created the extension later on.

Might be useful to ping @seriousscorpion @matsch55 and @mkaszub as they contributed to the extension, so it would be cool to have their feedback and awareness :)

**Comment by mkaszub** [comment]
Hey @buderre
That's a good point.  As Service Fabric is cloud independent it most likely should not be in azure extension.

**Comment by buderre** [comment]
I would not like to throw it away. It could be a positive option to separate it in two extensions - the Azure and the Service Fabric extension? This suggestion could on one side help us in the technical approach to separate those two extensions and on the other side increase the users' awareness for the Azure infrastructure extension.

This could have the charmant effect to update https://chaostoolkit.org/extensions with an additional extension and have two: Azure and Service Fabric as an extension.

I'm wondering what you think about this @mkaszub @Lawouach

**Comment by Lawouach** [comment]
If you folks feel like it's the right path, I'm more than happy to create a new repo called `chaostoolkit-azure-service-fabric`. It's a mouthful but clear :)

**Comment by matsch55** [comment]
That sounds good, but I would call it chaostoolkit-service-fabric, because service-fabrics could also be deloyed on AWS (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-standalone-create-infrastructure).

**Comment by Lawouach** [comment]
Sounds good by me! I'll create it now.

**Comment by Lawouach** [comment]
Done https://github.com/chaostoolkit-incubator/chaostoolkit-service-fabric

**Comment by Lawouach** [comment]
You may copy this extension over and clean it up as a PR. Or use a template project and start from scratch https://github.com/dastergon/cookiecutter-chaostoolkit

**Comment by buderre** [comment]
Nice one. Like it.
