### ISSUE TITLE
Refactoring the module structure

### ISSUE THREAD

**Issue by bugra-derre** [chaostoolkit-incubator/chaostoolkit-azure#95]
@Lawouach I would like to do a refactoring on the module structure.

Modules such as vm, vmss, and webapp have more or less similar (but not the same) actions. I would like to structure 

**from**
```
.
├── vm
│  ├── actions.py
├── vmss
│  ├── actions.py
├── webapp
│  ├── actions.py
```

**to**
```
.
│  compute
│  ├── vm
│  │  ├── actions.py
│  ├── vmss
│  │  ├── actions.py
│  ├── webapp
│  │  ├── actions.py
```

Would such a structure hurt somewhere e.g. the documentation generation?

**Comment by Lawouach** [comment]
Hey @bugra-derre 

I think that is fine but the documentation is not so much a problem (it's easy to change).
However, this will break all existing experiments using this extension.

One way would be to keep a helper function at the top of `chaosazure/__init__.py` that catches old calls and issue a deprecation warning.

**Comment by bugra-derre** [comment]
Ahh. True story. Okay. I think I will leave it as is and close this story.
